### ISSUE TITLE
Wrong balance calculation and display

### ISSUE THREAD

**Issue by pkerschbaumer** [LokCenter/AZN_Spring_WebClient#81]
Too much overtime is calculated on a few user accounts for the year 2024.
Issue appears on two user accounts starting in January 2024.
Here a user has excessive overtime of approximately 9 hours:

![MicrosoftTeams-image](https://github.com/LokCenter/AZN_Spring_WebClient/assets/122256592/6e5e567d-9704-4514-996b-05aebb3428d2)

[See the issue in AZN_Spring_ResourceServer for details on the problematic code.](https://github.com/LokCenter/AZN_Spring_ResourceServer/issues/101)

AZN_Spring_WebClient v1.1.5
AZN_Spring_ResourceServer v1.2.1

**Comment by lszillat** [comment]
Try accepting the previous months (it'l only work in a new Year after excepting December and optimally every month used in this year) and check again if it still exists.

**Comment by pkerschbaumer** [comment]
@lszillat
As far as I was told, the user's previous year was completely accepted at this point. I know you guys made the calculation of carried-over time from the previous year work that way intentionally, but since it didn't seem to have to do with that, I figured it was a weird edge case in the SQL calculation of the overtime. Should probably try that again anyway, just to be sure.

**Comment by pkerschbaumer** [comment]
Fixed in ResourceServer v1.2.3.
