### ISSUE TITLE
Outdated footer

### ISSUE THREAD

**Issue by pkerschbaumer** [LokCenter/AZN_Spring_WebClient#83]
Year and contributors in the footer of the site are out of date.
~Perhaps also add a link to GitHub issues for user-submitted bug reports, in case someone wants to do that.~

**Comment by lszillat** [comment]
You could just erase our names as we no longer maintain this Project and make the date automatically change and regarding the GitHub Link, you shouldn't expect the KBMs to make an GitHub account just for reporting bugs.

**Comment by pkerschbaumer** [comment]
@lszillat
If that's what you prefer, I will erase your names from the footer. The GitHub link was an idea I had floating around as a possible way for users to report bugs, but yes, considering you'd have to make an account it seems pretty useless now, since no one would go through the trouble for a slight annoyance (I forgot that an account was necessary).
